export enum SurvivalClassType {
  STANDARD = 'STANDARD',
  ENVIRONMENTAL = 'ENVIRONMENTAL',
  PSYCHOLOGICAL = 'PSYCHOLOGICAL',
  COMBINATION = 'COMBINATION',
  UTOPIAN = 'UTOPIAN',
  DYSTOPIAN = 'DYSTOPIAN',
  UNCLASSIFIED = 'UNCLASSIFIED',
  CHANGING = 'CHANGING',
  OTHER = 'OTHER',
}

export enum Legitimacy {
  VERIFIED = 'VERIFIED',
  UNVERIFIED = 'UNVERIFIED',
  DISPUTED = 'DISPUTED',
}